apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      serviceAccountName: dispatcher
      containers:
      - name: dispatcher
        image: gcr.io/trident-test-2020-08-24/dispatcher:0.1
        env:
        - name: PROJECT_ID
          value: trident-test-2020-08-24
        - name: RESULT_TOPIC_ID
          value: results
        - name: SUBSCRIPTION_ID
          value: dispatcher-credentials
        - name: WORKER_NAME
          value: webhook
        - name: WORKER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: dispatcher-worker
              key: config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-worker
  namespace: default
data:
  config: |
    {
      "url":"https://webhook-worker-ib43xp27wq-uc.a.run.app",
      "token": "3a6e2036db9f683eb5c9b02654c372da6a0ec55a179d219825c6292fe508b1af"
    }
