apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      serviceAccountName: orchestrator
      containers:
      - name: orchestrator
        image: gcr.io/trident-test-2020-08-24/orchestrator:0.22
        env:
        - name: CF_AUTH_DOMAIN
          value: https://krbtgt.cloudflareaccess.com
        - name: CF_AUDIENCE
          value: 1733a8a8e2077fe8659a48853c682804d9886abba51f715c83e898ae2f722e57
        - name: ADMIN_LISTENING_PORT
          value: "8000"
        - name: DB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: connection
        - name: PROJECT_ID
          value: trident-test-2020-08-24
        - name: TOPIC_ID
          value: credentials
        - name: SUBSCRIPTION_ID
          value: orchestrator-results
        - name: REDIS_URI
          value: 10.102.242.227:6379
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:latest
        command:
          - "/cloud_sql_proxy"
          - "-instances=trident-test-2020-08-24:us-central1:campaigns=tcp:5432"
        securityContext:
          runAsNonRoot: true
      - name: tunnel
        image: docker.io/cloudflare/cloudflared:2020.7.1
        imagePullPolicy: Always
        command: ["cloudflared", "tunnel"]
        args:
        - --url=http://127.0.0.1:8000
        - --hostname=trident.thortonmedia.com
        - --origincert=/etc/cloudflared/cert.pem
        - --no-autoupdate
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - mountPath: /etc/cloudflared
          name: tunnel-secret
          readOnly: true
      volumes:
      - name: tunnel-secret
        secret:
          secretName: tunnel-secret
